before_script:
    - mkdir -p ~/.gitlab-ci/npm/node_modules
    - ln -s ~/.gitlab-ci/npm/node_modules
    - npm install
    - git submodule init
    - git submodule update --remote

build:
    stage: build
    script:
        - webpack --optimize-minimize
        - mkdir -p kds519
        - cp -R dist img views kds519/
    artifacts:
        name: "3.0.9.$(date +%Y%m%d)"
        paths:
            - kds519/
